//! Differential tests against upstream DDS's own test data (`hands/list100.txt`,
//! `hands/masterDD.txt` from the vendored `v2.9.0` tag; docs/design/10-dds.md §8).
//!
//! Both files share one record format, 7 lines per deal (verified against the vendored
//! archive's `test/parse.cpp` and `src/Par.cpp`, since the shipped `hands/README` does not
//! document it):
//! ```text
//! PBN <dealer> <vul> <trump> <first> "<deal string>"
//! FUT <n> <n suits> <n ranks> <n equals> <n scores>      (SolveBoard reference; not checked here)
//! TABLE <20 ints>                                         resTable[strain][hand], DDS order
//! PAR "<NS score>" "<EW score>" "<NS contracts>" "<EW contracts>"   (legacy Par(); not checked)
//! PAR2 "<score>" "<contract>"...                          legacy DealerPar() text; score only
//! PLAY <n> "<2n hex-ish chars: suit+rank pairs>"
//! TRACE <n> <n ints>                                       solvedPlay.tricks[0..=n]
//! ```
//! `dealer`/`vul` use `DealerPar.cpp`'s own comment ("dealer 0 N 1 E 2 S 3 W", "vulnerable 0
//! None 1 Both 2 NS 3 EW" — note vul is *not* [`Vulnerability::from_index`]'s numbering, hence
//! `convert::vulnerability_from_dds`). `trump`/`first` are `SolveBoard`'s DDS strain/hand
//! encoding (`convert::strain_from_dds`, identity for seats).
//!
//! The `PAR`/`PAR2` *contract strings* are generated by DDS's legacy `DealerPar` text
//! formatter, a different function — with a different text format — from `DealerParBin`, which
//! this crate's `dealer_par` uses (docs/design/10-dds.md §7.1). Reconciling the two formats
//! exactly is out of scope; only `PAR2`'s numeric score (unambiguous either way) is compared.
#![cfg(dds_vendored)]

use std::path::{Path, PathBuf};

use bridge_core::{Card, Deal, PlayHistory, Rank, Seat, Suit, Vulnerability};
use bridge_dds::{analyse_play, calc_dd_table, convert, dealer_par};

/// `BRIDGE_CORPUS_DIR`, or `<workspace>/corpus/data`; `None` when the directory is absent
/// (matches the convention in `bridge-format/tests/common/mod.rs`).
fn corpus_dir() -> Option<PathBuf> {
    let dir = match std::env::var_os("BRIDGE_CORPUS_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../corpus/data"),
    };
    if dir.is_dir() {
        Some(dir)
    } else {
        eprintln!("corpus directory {} not found; skipping", dir.display());
        None
    }
}

/// One parsed `list100.txt`/`masterDD.txt` record.
struct Record {
    dealer: Seat,
    vul: Vulnerability,
    trump: bridge_core::Strain,
    leader: Seat,
    deal: Deal,
    table: [[i32; 4]; 5],
    par_score: i32,
    play: Vec<Card>,
    trace: Vec<i32>,
}

/// The substrings between successive pairs of `"`, in order.
fn quoted_tokens(line: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = line;
    while let Some(start) = rest.find('"') {
        let after = &rest[start + 1..];
        let Some(end) = after.find('"') else { break };
        out.push(&after[..end]);
        rest = &after[end + 1..];
    }
    out
}

fn ints_after_tag(line: &str) -> Vec<i64> {
    line.split_whitespace()
        .skip(1)
        .map(|t| {
            t.parse()
                .unwrap_or_else(|e| panic!("{t:?} in {line:?}: {e}"))
        })
        .collect()
}

fn parse_pbn_line(line: &str) -> (i32, i32, i32, i32, &str) {
    let head_end = line.find('"').unwrap_or(line.len());
    let mut nums = line[..head_end].split_whitespace();
    assert_eq!(nums.next(), Some("PBN"), "{line:?}");
    let dealer = nums.next().unwrap().parse().unwrap();
    let vul = nums.next().unwrap().parse().unwrap();
    let trump = nums.next().unwrap().parse().unwrap();
    let first = nums.next().unwrap().parse().unwrap();
    let deal_str = quoted_tokens(line)
        .into_iter()
        .next()
        .unwrap_or_else(|| panic!("no quoted deal string in {line:?}"));
    (dealer, vul, trump, first, deal_str)
}

fn parse_table_line(line: &str) -> [[i32; 4]; 5] {
    let nums = ints_after_tag(line);
    assert_eq!(nums.len(), 20, "TABLE line {line:?}");
    let mut table = [[0i32; 4]; 5];
    for (s, row) in table.iter_mut().enumerate() {
        for (h, cell) in row.iter_mut().enumerate() {
            *cell = nums[4 * s + h] as i32;
        }
    }
    table
}

fn parse_par2_score(line: &str) -> i32 {
    let tokens = quoted_tokens(line);
    assert!(!tokens.is_empty(), "PAR2 line {line:?}");
    tokens[0]
        .parse()
        .unwrap_or_else(|e| panic!("PAR2 score {:?} in {line:?}: {e}", tokens[0]))
}

fn parse_play_line(line: &str) -> Vec<Card> {
    let s = quoted_tokens(line)
        .into_iter()
        .next()
        .unwrap_or_else(|| panic!("no quoted play string in {line:?}"));
    let chars: Vec<char> = s.chars().collect();
    assert_eq!(chars.len() % 2, 0, "odd-length play string {s:?}");
    chars
        .chunks_exact(2)
        .map(|pair| {
            let suit = Suit::ALL
                .into_iter()
                .find(|su| su.letter() == pair[0])
                .unwrap_or_else(|| panic!("unknown suit letter {:?} in {s:?}", pair[0]));
            let rank = Rank::ALL
                .into_iter()
                .find(|r| r.to_char() == pair[1])
                .unwrap_or_else(|| panic!("unknown rank char {:?} in {s:?}", pair[1]));
            Card::new(suit, rank)
        })
        .collect()
}

fn parse_trace_line(line: &str) -> Vec<i32> {
    let mut nums = ints_after_tag(line).into_iter();
    let n = nums.next().expect("TRACE line has a count") as usize;
    let tricks: Vec<i32> = nums.map(|v| v as i32).collect();
    assert_eq!(tricks.len(), n, "TRACE line {line:?}");
    tricks
}

fn parse_records(path: &Path) -> Vec<Record> {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let mut lines = text.lines();
    let header = lines.next().expect("non-empty file");
    let count: usize = header
        .split_whitespace()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| panic!("expected 'NUMBER <n>', got {header:?}"));

    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let rec_lines: Vec<&str> = (0..7)
            .map(|_| lines.next().expect("7 lines per record"))
            .collect();
        let (dealer, vul, trump, first, deal_str) = parse_pbn_line(rec_lines[0]);
        let deal: Deal = deal_str
            .parse()
            .unwrap_or_else(|e| panic!("deal string {deal_str:?}: {e:?}"));
        records.push(Record {
            dealer: Seat::from_index(dealer as u8),
            vul: convert::vulnerability_from_dds(vul),
            trump: convert::strain_from_dds(trump),
            leader: Seat::from_index(first as u8),
            deal,
            table: parse_table_line(rec_lines[2]),
            par_score: parse_par2_score(rec_lines[4]),
            play: parse_play_line(rec_lines[5]),
            trace: parse_trace_line(rec_lines[6]),
        });
    }
    records
}

/// Runs the three checks (`TABLE`, `TRACE`, `PAR2` score) over `records`, returning
/// `(table_matches, trace_matches, par_matches)`.
fn check_all(records: &[Record]) -> (usize, usize, usize) {
    let (mut table_ok, mut trace_ok, mut par_ok) = (0, 0, 0);
    for rec in records {
        let table = calc_dd_table(&rec.deal).expect("calc_dd_table should not fail");
        let matches = (0..5).all(|s| {
            let strain = convert::strain_from_dds(s as i32);
            (0..4).all(|h| {
                let seat = Seat::from_index(h as u8);
                i32::from(table.tricks(strain, seat)) == rec.table[s][h]
            })
        });
        if matches {
            table_ok += 1;
        } else {
            eprintln!(
                "TABLE mismatch for {}: expected {:?}, got {:?}",
                rec.deal,
                rec.table,
                table.as_array()
            );
        }

        match dealer_par(&table, rec.dealer, rec.vul) {
            Ok(par) if par.score == rec.par_score => par_ok += 1,
            Ok(par) => eprintln!(
                "PAR score mismatch for {}: expected {}, got {} ({:?})",
                rec.deal, rec.par_score, par.score, par.contracts
            ),
            Err(e) => eprintln!("dealer_par failed for {}: {e}", rec.deal),
        }

        let mut history = PlayHistory::new(rec.trump, rec.leader);
        let mut legal = true;
        for &card in &rec.play {
            let actor = history.next_to_play();
            if let Err(e) = history.play(card, rec.deal.hand(actor)) {
                eprintln!("illegal play {card} for {}: {e}", rec.deal);
                legal = false;
                break;
            }
        }
        if !legal {
            continue;
        }
        match analyse_play(&rec.deal, &history) {
            Ok(tricks) => {
                let got: Vec<i32> = tricks.iter().map(|&t| i32::from(t)).collect();
                if got == rec.trace {
                    trace_ok += 1;
                } else {
                    eprintln!(
                        "TRACE mismatch for {}: expected {:?}, got {:?}",
                        rec.deal, rec.trace, got
                    );
                }
            }
            Err(e) => eprintln!("analyse_play failed for {}: {e}", rec.deal),
        }
    }
    (table_ok, trace_ok, par_ok)
}

/// The required differential test: `calc_dd_table` against every `TABLE` line, `analyse_play`
/// against every `PLAY`/`TRACE` pair, and `dealer_par`'s score against every `PAR2` score, for
/// all 100 deals of `hands/list100.txt`. Not `#[ignore]`d: this file is small (100 deals) and
/// this is the primary correctness gate for the wrapper (docs/design/12-roadmap.md 5.6).
#[test]
fn list100_matches_upstream() {
    let Some(dir) = corpus_dir() else { return };
    let path = dir.join("dds/list100.txt");
    if !path.is_file() {
        eprintln!("{} not found; skipping", path.display());
        return;
    }
    let records = parse_records(&path);
    let total = records.len();
    assert!(total > 0, "empty {}", path.display());

    let (table_ok, trace_ok, par_ok) = check_all(&records);
    eprintln!(
        "list100: TABLE {table_ok}/{total}, TRACE {trace_ok}/{total}, PAR2 score {par_ok}/{total}"
    );
    assert_eq!(table_ok, total, "calc_dd_table vs TABLE");
    assert_eq!(trace_ok, total, "analyse_play vs TRACE");
    assert_eq!(par_ok, total, "dealer_par score vs PAR2");
}

/// The full corpus (83,691 deals): slow (tens of minutes), so `#[ignore]`.
/// Run with `cargo test --release -p bridge-dds -- --ignored`.
#[test]
#[ignore = "83,691 deals; run with `cargo test --release -p bridge-dds -- --ignored`"]
fn masterdd_matches_upstream() {
    let Some(dir) = corpus_dir() else { return };
    let path = dir.join("dds/masterDD.txt");
    if !path.is_file() {
        eprintln!("{} not found; skipping", path.display());
        return;
    }
    let records = parse_records(&path);
    let total = records.len();
    assert!(total > 0, "empty {}", path.display());

    let (table_ok, trace_ok, par_ok) = check_all(&records);
    eprintln!(
        "masterDD: TABLE {table_ok}/{total}, TRACE {trace_ok}/{total}, PAR2 score {par_ok}/{total}"
    );
    assert_eq!(table_ok, total, "calc_dd_table vs TABLE");
    assert_eq!(trace_ok, total, "analyse_play vs TRACE");
    assert_eq!(par_ok, total, "dealer_par score vs PAR2");
}
